using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HobiHobi.Core.Subscriptions;
using NUnit.Framework;

namespace HobiHobi.Tests.Core.Subscriptions
{
    [TestFixture]
    public class RssSubscriptionTests
    {
        [Test]
        public void LoadFromOPML()
        {
            var opml = new Opml();
            opml.LoadFromXML(_sample);
            var subscription = new RssSubscription(opml);

            Assert.IsTrue(subscription.Items.Count > 0);
            var item1 = subscription.Items.First();
            Assert.IsNotNullOrEmpty(item1.Title);
            Assert.IsNotNullOrEmpty(item1.Text);
            Assert.IsNotNullOrEmpty(item1.Name);
            Assert.IsNotNullOrEmpty(item1.Description);
            Assert.IsNotNullOrEmpty(item1.HtmlUri.ToString());
            Assert.IsNotNullOrEmpty(item1.XmlUri.ToString());
        }

        string _sample = @"<?xml version=""1.0"" encoding=""ISO-8859-1""?>

<!-- OPML generated by OPML Editor v11.0.6 on Sat, 11 Aug 2012 12:43:48 GMT -->

<opml version=""2.0"">

	<head>

		<title>apple.opml</title>

		<dateCreated>Fri, 10 Aug 2012 13:17:48 GMT</dateCreated>

		<dateModified>Sat, 11 Aug 2012 12:43:48 GMT</dateModified>

		<ownerName>Dave Winer</ownerName>

		<ownerEmail>dave.winer@gmail.com</ownerEmail>

		<expansionState></expansionState>

		<vertScrollState>1</vertScrollState>

		<windowTop>298</windowTop>

		<windowLeft>1379</windowLeft>

		<windowBottom>995</windowBottom>

		<windowRight>2117</windowRight>

		</head>

	<body>

		<outline text=""9to5Mac"" description=""Apple Intelligence"" htmlUrl=""http://9to5mac.com"" name=""9to5mac"" title=""9to5Mac"" type=""rss"" xmlUrl=""http://feeds.feedburner.com/9To5Mac-MacAllDay""/>

		<outline text=""And now it's all this"" htmlUrl="""" name=""andNowItsAllThis"" title=""And now itâ€™s all this"" type=""rss"" xmlUrl=""http://www.leancrew.com/all-this/feed/""/>

		<outline text=""Andy Ihnatko's Celestial Waste of Bandwidth (BETA)"" htmlUrl="""" title=""Andy Ihnatko's Celestial Waste of Bandwidth (BETA)"" type=""rss"" xmlUrl=""http://ihnatko.com/feed/""/>

		<outline text=""Apple Outsider"" htmlUrl="""" title=""Apple Outsider"" type=""rss"" xmlUrl=""http://www.appleoutsider.com/feed""/>

		<outline text=""AppleInsider"" description=""AppleInsider has been the leading source of insider news and rumors on Apple Computer since 1997."" htmlUrl=""http://www.appleinsider.com/"" name=""appleinsider"" title=""AppleInsider"" type=""rss"" xmlUrl=""http://appleinsider.com.feedsportal.com/c/33975/f/616168/index.rss""/>

		<outline text=""Ars Technica Infinite Loop"" htmlUrl=""http://arstechnica.com"" name=""arsTechnicaInfiniteLoop"" title=""Ars Technica Â» Infinite Loop"" type=""rss"" xmlUrl=""http://feeds.arstechnica.com/arstechnica/apple""/>

		<outline text=""CNET News - Apple"" htmlUrl=""http://news.cnet.com/8300-13579_3-.html"" name=""cnetNewsApple"" title=""CNET News - Apple"" type=""rss"" xmlUrl=""http://news.cnet.com/8300-13579_3-37.xml""/>

		<outline text=""Coyote Tracks"" htmlUrl=""http://tracks.ranea.org/"" title=""Coyote Tracks"" type=""rss"" xmlUrl=""http://tracks.ranea.org/rss""/>

		<outline text=""Daring Fireball"" htmlUrl=""http://daringfireball.net/"" name=""daringFireball"" title=""Daring Fireball"" type=""rss"" xmlUrl=""http://daringfireball.net/index.xml""/>

		<outline text=""David Smith"" htmlUrl=""http://"" name=""davidSmith"" title=""David Smith"" type=""rss"" xmlUrl=""http://david-smith.org/atom.xml""/>

		<outline text=""Fortune Tech: Technology blogs, news and analysis from Fortune Magazine » Apple"" htmlUrl="""" title=""Fortune Tech: Technology blogs, news and analysis from Fortune Magazine » Apple"" type=""rss"" xmlUrl=""http://tech.fortune.cnn.com/tag/apple/feed""/>

		<outline text=""Gizmodo: Apple"" htmlUrl=""http://gizmodo.com/tag/apple"" title=""Gizmodo: Apple"" type=""rss"" xmlUrl=""http://gizmodo.com/apple/index.xml""/>

		<outline text=""iMore - The #1 iPhone, iPad, and iPod touch blog"" htmlUrl=""http://www.imore.com"" title=""iMore - The #1 iPhone, iPad, and iPod touch blog"" type=""rss"" xmlUrl=""http://feeds.feedburner.com/TheiPhoneBlog""/>

		<outline text=""inessential.com"" htmlUrl=""http://inessential.com/"" name=""inessentialcom"" title=""inessential.com"" type=""rss"" xmlUrl=""http://inessential.com/xml/rss.xml""/>

		<outline text=""John Moltz's Very Nice Web Site"" htmlUrl=""http://verynicewebsite.net"" title=""John Moltz's Very Nice Web Site"" type=""rss"" xmlUrl=""http://verynicewebsite.net/feed/atom/""/>

		<outline text=""kickingbear"" htmlUrl="""" title=""kickingbear"" type=""rss"" xmlUrl=""http://kickingbear.com/blog/feed""/>

		<outline text=""MacInTouch"" htmlUrl=""http://www.macintouch.com/"" name=""macintouch"" title=""MacInTouch"" type=""rss"" xmlUrl=""http://www.macintouch.com/rss.xml""/>

		<outline text=""MacRumors: Mac News and Rumors - All Stories"" description=""the mac news you care about"" htmlUrl=""http://www.macrumors.com"" name=""macrumorsMacNewsAndRumorsAllStories"" title=""MacRumors: Mac News and Rumors - All Stories"" type=""rss"" xmlUrl=""http://feeds.macrumors.com/MacRumors-All""/>

		<outline text=""MacStories"" htmlUrl=""http://www.macstories.net"" name=""macstories"" title=""MacStories"" type=""rss"" xmlUrl=""http://feeds.feedburner.com/macstoriesnet""/>

		<outline text=""Manton Reece"" htmlUrl=""http://www.manton.org/"" title=""Manton Reece"" type=""rss"" xmlUrl=""http://www.manton.org/rss.xml""/>

		<outline text=""Marco.org"" htmlUrl=""http://www.marco.org/"" name=""marcoorg"" title=""Marco.org"" type=""rss"" xmlUrl=""http://www.marco.org/rss""/>

		<outline text=""Matt Gemmell"" htmlUrl=""http://"" name=""mattGemmell"" title=""Matt Gemmell"" type=""rss"" xmlUrl=""http://mattgemmell.com/feed""/>

		<outline text=""MyAppleMenu by Heng-Cheong Leong"" htmlUrl=""http://www.myapplemenu.com/"" title=""MyAppleMenu by Heng-Cheong Leong"" type=""rss"" xmlUrl=""http://www.myapplemenu.com/rss.xml""/>

		<outline text=""NYT &gt; Apple Incorporated"" htmlUrl=""http://topics.nytimes.com/top/news/business/companies/apple_computer_inc/index.html?8qa&amp;"" title=""NYT &gt; Apple Incorporated"" type=""rss"" xmlUrl=""http://topics.nytimes.com/top/news/business/companies/apple_computer_inc/index.html?8qa&amp;rss=1""/>

		<outline text=""Observatory &gt;&gt; Blog"" htmlUrl="""" name=""observatoryBlog"" title=""Observatory » Blog"" type=""rss"" xmlUrl=""http://kensegall.com/blog/feed""/>

		<outline text=""OS X Daily"" htmlUrl=""http://osxdaily.com"" name=""osXDaily"" title=""OS X Daily"" type=""rss"" xmlUrl=""http://feeds.feedburner.com/osxdaily""/>

		<outline text=""Red Sweater Blog"" htmlUrl="""" title=""Red Sweater Blog"" type=""rss"" xmlUrl=""http://www.red-sweater.com/blog/feed/""/>

		<outline text=""SplatF"" htmlUrl=""http://www.splatf.com"" title=""SplatF"" type=""rss"" xmlUrl=""http://feeds.splatf.com/splatf""/>

		<outline text=""Technology: Apple | guardian.co.uk"" htmlUrl=""http://www.guardian.co.uk/technology/apple"" name=""technologyAppleGuardiancouk"" title=""Technology: Apple | guardian.co.uk"" type=""rss"" xmlUrl=""http://www.guardian.co.uk/technology/apple/rss""/>

		<outline text=""The Loop"" htmlUrl=""http://www.loopinsight.com"" name=""theLoop"" title=""The Loop"" type=""rss"" xmlUrl=""http://feeds.feedburner.com/loopinsight/KqJb""/>

		<outline text=""The Verge -  Apple Posts"" htmlUrl=""http://www.theverge.com/apple"" name=""theVergeApplePosts"" title=""The Verge -  Apple Posts"" type=""rss"" xmlUrl=""http://www.theverge.com/apple/rss/index.xml""/>

		<outline text=""TUAW - The Unofficial Apple Weblog"" htmlUrl=""http://www.tuaw.com"" name=""tuawTheUnofficialAppleWeblog"" title=""TUAW - The Unofficial Apple Weblog"" type=""rss"" xmlUrl=""http://www.tuaw.com/rss.xml""/>

		<outline text=""Untitled"" htmlUrl=""http://"" title=""Untitled"" type=""rss"" xmlUrl=""http://developer.apple.com/news/rss/news.rss""/>

		</body>

	</opml>
";
    }
}
